fix: add sleep timer on web package publishing, and check for workflow run success

diff --git a/.github/workflows/upload-cdn.yml b/.github/workflows/upload-cdn.yml
--- a/.github/workflows/upload-cdn.yml
+++ b/.github/workflows/upload-cdn.yml
@@ -17,16 +17,18 @@ env:
 
 jobs:
   unable-to-deploy:
-      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
-      runs-on: ubuntu-latest
-      steps:
-        - name: Exit and notify Slack if publishing failed and we can't upload to the CDN
-          run: |
-            json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Publishing workflow failed, unable to upload to CDN <https://github.com/cds-snc/gcds-components/actions/workflows/upload-cdn.yml|Upload packages to CDN>"}}]}'
-            curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SLACK_WEBHOOK_OPS }}
-            exit 1
+    # If this was triggered by a workflow run ("Publish packages" as noted above) and the workflow run failed
+    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Exit and notify Slack if publishing failed and we can't upload to the CDN
+        run: |
+          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Publishing workflow failed, unable to upload to CDN <https://github.com/cds-snc/gcds-components/actions/workflows/upload-cdn.yml|Upload packages to CDN>"}}]}'
+          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SLACK_WEBHOOK_OPS }}
+          exit 1
 
   upload-to-cdn:
+    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
     runs-on: ubuntu-latest
 
     strategy:
